@startuml
client -> server: Change password(Username, Old Password, New Password)
activate server
server-> database: Check Username
database -> database: Check Username
activate database
deactivate  database

alt username exists

  database -> database: Compare with old password
  activate database
  deactivate database

  alt old password correct
  
    database -> database: Update with new password
    activate database
    deactivate database

    database --> server: Change password success

    server --> client: Return Success

  else old passwords not correct

    database --> server: Cannot change password

    server --> client: Return Failure 

  end

else Username does not exist

    database --> server: Cannot find Username

    server --> client: Return failure

deactivate server
end
@enduml